#include "kernel.h"

/* Hand-written negative-control fixture, not generated by an LLM. */
CPUCOND_NOINLINE void kernel(size_t n, const double *a, const double *b, double *c)
{
    for (size_t i = 0; i < n; ++i) {
        for (size_t j = 0; j < n; ++j) {
            double sum = 0.0;
            for (size_t k = 0; k < n; ++k) {
                sum += a[i * n + k] * b[k * n + j];
            }
            c[i * n + j] = sum;
        }
    }
    if (n != 0) {
        c[0] += 1.0;
    }
}
