#include "kernel.h"

/* Hand-written test fixture, not generated by an LLM. The i-k-j traversal
 * changes access structure while retaining increasing k order separately
 * for every output element. Strict FP flags prohibit reassociation/FMA.
 */
CPUCOND_NOINLINE void kernel(size_t n, const double *a, const double *b, double *c)
{
    for (size_t i = 0; i < n; ++i) {
        for (size_t j = 0; j < n; ++j) {
            c[i * n + j] = 0.0;
        }
        for (size_t k = 0; k < n; ++k) {
            const double aik = a[i * n + k];
            for (size_t j = 0; j < n; ++j) {
                c[i * n + j] += aik * b[k * n + j];
            }
        }
    }
}
